config/routes.rb
Rails.application.routes.draw do
  get 'plans/mobile', to: 'plans#mobile'

  get 'plans/nbn', to: 'plans#nbn'

  get 'plans/data_only', to: 'plans#data_only'

  root to: 'pages#homepage'

  get 'help/mobile', to: 'pages#help'
  #go to page controller and help action
  get 'plans/mobile-plans', to: 'plans#mobile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def help
    @name = 'Kevin'
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def mobile
  end

  def nbn
  end

  def data_only
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_container.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p> <img src="https://www.amaysim.com.au/sites/default/files/2017-04/lock_dash_mint.svg"> no lock-in contracts </p>
      <p>Freedom to switch your plan or cancel at anytime.</p>
    </div>
    <div class="col">
      <p> <img src= "https://www.amaysim.com.au/sites/default/files/2017-04/join_dash_mint.svg"> simple to join </p>
      <p>Quick and easy online sign-up, we’ll take care of all the fiddly bits.</p>
    </div>
    <div class="col">
      <p> <img src= "https://www.amaysim.com.au/sites/default/files/2017-04/app_dash_mint.svg"> easy to manage </p>
      <p>Download our app or manage your plans online.</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <img src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout_2x/public/cta/2017-05/mobile%20plans.png?itok=69f-sg5G" height="300px" width="300px">

    </div>
    <div class="col">
      <img src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout_2x/public/cta/2017-05/nbn.png?itok=YemmV9dC" height="300px" width="300px">

    </div>
    <div class="col">
      <img src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout_2x/public/cta/2017-05/data%20only.png?itok=dGtEaTb5" height="300px" width="300px">
  
    </div>
  </div>

app/views/layouts/_container2.html.erb
<div class= "PurpleBanner">

  <div class="container">
    <div class="row">
      <div class="col">
        1 of 3
      </div>
      <div class="col-6">
        2 of 3 (wider)
      </div>
      <div class="col">
        3 of 3
      </div>
    </div>
  </div>

app/views/layouts/_nav.html.erb
<!-- # _ signifies partial -->

<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  <div class="container">
  <a class="navbar-brand text-white" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li> -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          plans
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/plans/mobile">mobile plans</a>
          <a class="dropdown-item" href="#">nbn plans</a>
          <a class="dropdown-item" href="#">data-only plans</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          about
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">who we are</a>
          <a class="dropdown-item" href="#">why amaysim</a>
          <a class="dropdown-item" href="#">check mobile network coverage</a>
          <a class="dropdown-item" href="#">Find a store</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          help
        </a>
        <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div> -->
      </li>


      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amaysim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <a href="/help/mobile">Help</a> -->
    <!-- <%= link_to 'Help', help_mobile_path %> -->
    <!-- <%= link_to 'Help URL', help_mobile_path %> -->
    <%= render 'layouts/nav'%>
    <%= render 'layouts/container2'%>
    <%= render 'layouts/container'%>


    <%= yield %>

  </body>
</html>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

<h1>
  <%= @name %>
</h1>

app/views/pages/homepage.html.erb
<h1>Pages#homepage</h1>
<p>Find me in app/views/pages/homepage.html.erb</p>

app/views/plans/data_only.html.erb
<h1>Plans#data_only</h1>
<p>Find me in app/views/plans/data_only.html.erb</p>

app/views/plans/mobile.html.erb
<h1>Plans#mobile</h1>
<p>Find me in app/views/plans/mobile.html.erb</p>

app/views/plans/nbn.html.erb
<h1>Plans#nbn</h1>
<p>Find me in app/views/plans/nbn.html.erb</p>